modLoader="javafml"
loaderVersion="[35,)" 

license="MIT Liscense"
issueTrackerURL="https://github.com/NotUnfound/SmoothFocus/issues"

[[mods]]

	modId="smoothfocus"

	version="1.2.2"
	
	displayName="SmoothFocus"
	
	displayURL="https://www.curseforge.com/minecraft/mc-mods/smoothfocus"
	
	logoFile="logo.png"

	authors="NotUnfound"

	description='''A client-side only configureable zoom mod.'''
	

