modLoader="javafml"
loaderVersion="[35,)" 

license="MIT Liscense"
issueTrackerURL="https://nothing.net/srslynothinghere/goaway"

[[mods]]

	modId="smoothfocus"

	version="1.0"
	
	displayName="SmoothFocus"
	
	displayURL="https://www.curseforge.com/"
	
	logoFile="logo.png"

	authors="NotUnfound"

	description='''A client-side only configureable zoom mod.'''
	

